DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS post;

CREATE TABLE user (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    username TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL,
    steam_id INTEGER NOT NULL
);

CREATE TABLE player (
	steam_id INTEGER PRIMARY KEY AUTOINCREMENT,
	is_public INTEGER NOT NULL,
	name TEXT NOT NULL,
	url TEXT NOT NULL,
	avatar_url TEXT NOT NULL,
	time_created TIMESTAMP NOT NULL,
	update_time TIMESTAMP NOT NULL,
);

CREATE TABLE post (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    author_id INTEGER NOT NULL,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    title TEXT NOT NULL,
    body TEXT NOT NULL,
    FOREIGN KEY (author_id) REFERENCES user (id)
);
